name: Frontend Validation

on:
  push:
    branches: [ main]
    paths: 
      - 'src/resources/**'
      - 'src/package.json'
      - 'src/package-lock.json'
      - 'src/vite.config.ts'
      - 'src/tsconfig.json'
      - 'src/eslint.config.js'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/resources/**'
      - 'src/package.json'
      - 'src/package-lock.json'
      - 'src/vite.config.ts'
      - 'src/tsconfig.json'
      - 'src/eslint.config.js'

permissions:
  contents: read

jobs:
  frontend-validation:
    runs-on: ubuntu-latest
    
    timeout-minutes: 15
    
    defaults:
      run:
        working-directory: ./src

    strategy:
      matrix:
        node-version: [20.x]
      
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          
          fetch-depth: 1

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: src/package-lock.json
          
          registry-url: 'https://registry.npmjs.org'

      - name: Run security audit
        run: npm audit --audit-level=high

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check code formatting with Prettier
        run: npm run format:check

      - name: TypeScript type checking
        run: npx vue-tsc --noEmit

      - name: Build frontend for production
        run: npm run build

      - name: Build SSR
        run: npm run build:ssr
